apiVersion: workshop.gotopple.com/v1alpha1
kind: Paper
metadata:
  name: second-paper
spec:
        writer: Portia
        kind: memo
        data: >
          Dear reader,

          This is an entirely different document schema. This document uses "writer"
          instead of "author," "kind" instead of "type," and "data" in place of 
          "content." You are able to create both the "first-paper" and "second-paper" 
          resources as the same Kind because there are no validators on the type.

          Enjoy,
          Portia
